load("//bzl:module.bzl", "isaac_app", "isaac_subgraph")


isaac_app(
    name = "ros_conv",
    data = [
    ],
    modules = [
        "sensors:v4l2_camera",
        "sight",
				"behavior_tree",
				"ros_bridge",
				"viewers",
    ],
    tags = ["manual"],
)

